<?php
/**
 * General settings
 *
 * @copyright Copyright (c) 2017, hugw.io
 * @author Hugo W - me@hugw.io
 * @license GPLv2
 */

if( ! function_exists('acf_add_options_page') ) return;

add_action( 'after_setup_theme', function() {
  acf_add_options_sub_page([
    'page_title' 	=> __( 'General Settings', 'bloom' ) ,
    'menu_title'	=> __( 'General', 'bloom' ) ,
    'parent_slug'	=> 'theme-settings',
    'menu_slug'   => 'theme-settings-general',
    'autoload'    => true,
  ]);

  acf_add_local_field_group([
    'key' => 'group_8BiAv53IJw',
    'title' => __( 'General', 'bloom' ),
    'fields' => [
      [
        'key' => 'tab_DG9LSxZerW',
        'label' => __( 'Social Media', 'bloom' ),
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'subgroup_NJF83uR2VU',
        'label' => '',
        'name' => 'social_media',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'row',
        'sub_fields' => [
          [
            'key' => 'field_9H8K5zhVZE',
            'label' => 'Twitter URL',
            'name' => 'twitter',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_dirGgD9IUq',
            'label' => 'Facebook URL',
            'name' => 'facebook',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_uMwS81wIV6',
            'label' => 'Google Plus URL',
            'name' => 'googleplus',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_WwGQBIMUrc',
            'label' => 'Instagram URL',
            'name' => 'instagram',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_SPZ5JOsVJ7',
            'label' => 'Flickr URL',
            'name' => 'flickr',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_W3budhlorJ',
            'label' => 'Dribbble URL',
            'name' => 'dribbble',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_oQbNWI9uBi',
            'label' => 'Bitbucket URL',
            'name' => 'bitbucket',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_QouKZ5oKh8',
            'label' => 'Github URL',
            'name' => 'github',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_Q9DqltNvEl',
            'label' => 'Pinterest URL',
            'name' => 'pinterest',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_i2oqpM9FDz',
            'label' => 'Vimeo URL',
            'name' => 'vimeo',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_JmQ0WNxF3n',
            'label' => 'RSS URL',
            'name' => 'rss',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ]
        ],
      ],
      [
        'key' => 'tab_Vb5Li2yeIZ',
        'label' => __( 'Analytics', 'bloom' ),
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'subgroup_cY9fP0v7RX',
        'label' => '',
        'name' => 'analytics',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'row',
        'sub_fields' => [
          [
            'key' => 'field_BtHnOjA1vW',
            'label' => __( 'Code', 'bloom' ),
            'name' => 'code',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'placeholder' => '',
          ],
          [
            'key' => 'field_zdh8jUDGk2',
            'label' => __( 'Target', 'bloom' ),
            'name' => 'target',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'choices' => [
              'all' => 'All',
              'no_users' => 'No users',
              'no_admins' => 'No admins',
            ],
            'allow_null' => 0,
            'default_value' => 'all',
            'layout' => 'horizontal',
            'return_format' => 'value',
          ]
        ],
      ],
    ],
    'location' => [
      [
        [
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'theme-settings-general',
        ],
      ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ]);
});
